import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "@/context/toast-context";
import Sidebar from "@/components/side_bar/Sidebar";
import { NavbarDemo } from "@/components/navbar/navbar";
import { AuthProvider } from "@/context/authContext";
import Footer from "@/components/footer/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastProvider>
          <AuthProvider>
            <NavbarDemo />
            <Sidebar />
            {children}
            <Footer />
          </AuthProvider>
        </ToastProvider>

      </body>
    </html>
  );
}
